Use Fractal to organise and document components
nhsuk-archive/frontend-version-one pull request #3
Opened 2017-02-21 14:14 UTC by tyom

Reorganise components to use with Clearleft's [Fractal](http://fractal.build/).

This includes basic global CSS components that can be used on other NHS.UK sites. The static [documentation site](https://nhsuk.github.io/frontend/0.1.0/) is also generated.

2017-02-21 15:00 UTC, r4vi commented on README.md
> +  autoescape: true
this is the default: (from nunjucks/src/environment.js)
    // The autoescape flag sets global autoescaping. If true,
    // every string variable will be escaped by default.
    // If false, strings can be manually escaped using the `escape` filter.
    // defaults to true
    this.opts.autoescape = opts.autoescape != null ? opts.autoescape : true;

2017-02-21 15:08 UTC, tyom commented on README.md
> +  autoescape: true
I added it there just as an example to show that following the array of paths is the configuration object.

2017-02-22 18:26 UTC, teneightfive commented on README.md
> +  - `body_site_header` - wraps side header
Typo - _side_ should be _site_

2017-02-22 18:39 UTC, teneightfive commented on src/scss/components/01-global-header/_global-header.scss
> +  @media(min-resolution: 192dpi) {
Does auto prefixer handle the variations for this that we currently include in a mixin?

2017-02-23 10:39 UTC, tyom commented on src/scss/components/01-global-header/_global-header.scss
> +  @media(min-resolution: 192dpi) {
Autoprefixer gives a pretty good range which seemingly falls into what we specify in the config. Looking at caniuse.com browser support for [this feature](http://caniuse.com/#feat=css-media-resolution) I can see that `-webkit` and unprefixed version covers most of the use cases (IE9+, FF16+, Opera 12.1+, Chrome etc).

I don't see any value in adding very edge case prefixes. Only to increase complexity by having to use and maintain mixins.

2017-02-23 11:47 UTC, teneightfive commented
Is the purpose of the number prefix on component folders to determine display order? Not sure I like the idea of it being determined by the folder name. If we want to re-order in the future or add a component in between item 5 and 6 and we have 15 components that change would create an unnecessarily large diff. 

Is there a problem with components being alphabetically ordered?

2017-02-23 11:56 UTC, teneightfive commented
We should also consider what components we actually want to offer with this package. It could be useful to break down things like the global header and footer into a component but there might not be a need for this to be displayed in the living styleguide if they come as part of the site chrome.

If we think of this as the things needed to create assemblies that have a consistent look across NHS.UK the template could be a separate part to the components that are used inside that layout.

2017-02-23 12:05 UTC, tyom commented
> Is the purpose of the number prefix on component folders to determine display order? Not sure I like the idea of it being determined by the folder name. If we want to re-order in the future or add a component in between item 5 and 6 and we have 15 components that change would create an unnecessarily large diff.

I agree with you. I soon realised it would be painful to reorder. I think there's a way to order components from meta data. Alphabetical is fine, I guess, but it helps to group certain things.

I'll try using meta data for this.

2017-02-23 12:07 UTC, tyom commented
> We should also consider what components we actually want to offer with this package. It could be useful to break down things like the global header and footer into a component but there might not be a need for this to be displayed in the living styleguide if they come as part of the site chrome.

I don't have a problem documenting global level components. But instead of breaking them up we could document the whole base template assembly.

2017-02-23 12:14 UTC, teneightfive commented
>I don't have a problem documenting global level components. But instead of breaking them up we could document the whole base template assembly.

Yep, that sounds like a sensible start. Reduces the noise in the living styleguide around components. I think a need of "I need the header and footer components..." would be met by the base template so we can remove them from the component list.

2017-02-23 16:31 UTC, teneightfive requested changes

2017-02-23 16:31 UTC, teneightfive commented on README.md
> +npm run fractal:build
The task has been renamed back to `docs:build` so needs replicating here.

2017-02-23 16:31 UTC, teneightfive commented on fractal.js
> +  }
Trailing comma consistency?

2017-02-23 16:31 UTC, teneightfive commented on fractal.js
> +fractal.web.set('static.path', paths.dist);
Remove semi-colons for consistency?

2017-02-23 16:31 UTC, teneightfive commented on fractal/theme/index.js
> +module.exports = customTheme;
No need for semi-colon

2017-02-23 16:32 UTC, teneightfive commented
Looks really good as a start for maintaining and sharing layouts and components.

2017-02-23 17:11 UTC, teneightfive approved these changes

2017-02-23 17:19 UTC, merged