Add `link-list` component
nhsuk-archive/frontend-version-one pull request #9
Opened 2017-03-16 16:59 UTC by teneightfive

This adds a new component for `link-list` which is currently
being used in the global footer and therefore, base layout.

2017-03-16 17:19 UTC, tyom commented
Maybe add a few more examples for modifiers?

2017-03-17 10:18 UTC, tyom requested changes

2017-03-17 10:18 UTC, tyom commented on src/scss/components/link-list/link-list.njk
> +    <li class="link-list--item">
Shouldn't this be `link-list__item`?

2017-03-17 11:53 UTC, teneightfive commented on src/scss/components/link-list/link-list.njk
> +    <li class="link-list--item">
It doesn't actually seem to be being used by the sass so maybe we can drop it?

Although the `numbered` modifier uses `li` which is not ideal when trying to stick to BEM.

I'll change to `__` as separator and use that within `numbered` modifier.

2017-03-17 11:58 UTC, tyom approved these changes

2017-03-17 12:07 UTC, merged